# Generated by Django 3.0.5 on 2020-05-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installments',
            name='Installment_To_Be_Paid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='clients',
            name='Image',
            field=models.ImageField(default='avatar.png', upload_to='pics'),
        ),
    ]
