# Generated by Django 3.0.5 on 2020-05-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0003_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='Penalty_Paid',
            field=models.FloatField(default=0),
        ),
    ]
