# Generated by Django 3.0.5 on 2020-05-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0004_penalty_penalty_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='Penalty_Paid_Date',
            field=models.DateField(default=None, null=True),
        ),
    ]
