# Generated by Django 3.0.5 on 2020-05-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0007_auto_20200521_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installments',
            name='Penalty',
        ),
    ]
