# Generated by Django 3.0.5 on 2020-05-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0011_auto_20200521_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
