# Generated by Django 3.0.5 on 2020-05-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0012_auto_20200525_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantor_documents',
            name='Image',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
