# Generated by Django 3.0.5 on 2020-05-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0013_auto_20200527_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantor_documents',
            name='Image',
            field=models.ImageField(blank=True, upload_to='Guarantor_Documents'),
        ),
    ]
