# Generated by Django 3.0.5 on 2020-06-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0015_auto_20200529_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='Knowns_Name',
            new_name='Reference_Name',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='Knowns_No',
            new_name='Reference_No',
        ),
    ]
